spring:
  application:
    name: store

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP

mail:
  port: 8080
  host: https://smpt.gmail.com

payment-gateway: payPal