spring:
  application:
    name: store
  datasource:
#    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    url: jdbc:mysql://127.0.0.1:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 9090

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP

mail:
  port: 8080
  host: https://smpt.gmail.com

payment-gateway: payPal